
title: Adam Etches # your name (or website title) here
logo: "/images/adametchesphoto.png?raw=true" # your photo (or logo) here
round-logo: true
description: > 
  <b>Git Pages:</b>   
  Various projects and work looking at data science in the context of insight. I like to focus on: tools and techniques, data visualisation and the data to value pipline
  <br><br>
  <b>Personal Links:</b> 
  <br><br>
  <a href="https://www.linkedin.com/in/adam-etches-4a58056/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/adametches">View My GitHub Profile</a>


url-pretty: "https://adametches.github.io/"
email: adam.etches@gmail.com
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

author:
  name: Adam Etches
  picture: "/images/adametchesphoto.jpeg?raw=true"